# .github/workflows/build.yml
name: Build Rust Binaries

on:
  push:
    tags:
      - 'v*'  # Run only on version tags like v1.0.0
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu]
    outputs:
      release_built: ${{ steps.set-output.outputs.release_built }}
    steps:
      - uses: actions/checkout@v4

      - name: Install mingw-w64
        run: sudo apt install mingw-w64

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build binaries in release mode
        run: cargo build --release --target ${{ matrix.target }}
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: passman-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/passman

